### ISSUE TITLE
FutureWarning: Using an implicitly registered datetime converter 

### ISSUE THREAD

**Issue by jorgelaranjo** [PacktPublishing/Forecasting-Time-Series-Data-with-Facebook-Prophet#1]
When executing `CELL 7` from `Chapter_01` re `Matplotlib` chart with implicit datetime converter the `FutureWarning` is shown.

```
FutureWarning: Using an implicitly registered datetime converter for a matplotlib plotting method. The converter was registered by pandas on import. Future versions of pandas will require you to explicitly register matplotlib converters.

To register the converters:
	>>> from pandas.plotting import register_matplotlib_converters
	>>> register_matplotlib_converters()
  warnings.warn(msg, FutureWarning)
```

Simple to fix by just adding

```
from pandas.plotting import 
register_matplotlib_convertersregister_matplotlib_converters()
```

**Comment by raffg** [comment]
I'm unable to duplicate the issue on either my laptop or a Google Colab. I suspect you've got an outdated package somewhere which needs to be updated.

**Comment by jorgelaranjo** [comment]
It is not an outdated package. 
The same issue was initially reported back in [2019](https://github.com/facebook/prophet/issues/999#issuecomment-500035319
)
It is present since Pandas version 0.24.2

Link for the technical explanation:
https://github.com/facebook/prophet/issues/999#issuecomment-500035319

> Basically what's happening is that when you import pandas, it registers with matplotlib a bunch of functions that tell matplotlib how to plot pandas types. But, it does more than just that - it actually overwrites some built-in matplotlib handlers with pandas handlers. In particular, matplotlib has built-in the ability to plot datetime objects. When pandas is imported, it overwrites matplotlib's built-in datetime plotting with pandas datetime plotting.

For reference, the versions I was using were:
| Lib  | Version |
| ------------- | ------------- |
| Pandas  | 1.2.3  |
| Matplotlib  | 3.4.1 |
| Numpy | 1.20.0 |

**Comment by raffg** [comment]
The chapter 1 notebook does not import Prophet, so the deregistering of converters which happens inside Prophet's `m.plot` should not ever occur in this notebook. Have you imported Prophet in your notebook before running that cell?

**Comment by jorgelaranjo** [comment]
Not a problem when not loading Prophet, thus assume it was because of having Prophet in memory at the time.
Also now using Prophet 1.0
