### ISSUE TITLE
Chapter 2 - Windows Installation

### ISSUE THREAD

**Issue by bmaschino** [PacktPublishing/Forecasting-Time-Series-Data-with-Facebook-Prophet#7]
When installing under Windows 10 with Anaconda3, the `conda install gcc` step could not find a valid package. I ended up following the directions from [this site](https://www.lucasmelin.com/getting-started-with-fbprophet-on-windows-10) and used the following C++ compiler steps

`conda install libpython m2w64-toolchain -c msys2`
`conda install -c conda-forge pystan==2.19.1.1`

**Comment by raffg** [comment]
Thanks for the tip, Bryce. Because of the C++ and Stan dependencies, installing Prophet can involve various steps depending upon the specific configuration of the machine and it isn't possible to write a comprehensive guide covering all scenarios. I'm glad you figured out how to get it working!
